# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_WAVE4_VPU) += wave4.o
wave4-objs +=  	wave4-hw.o \
		wave4-vpuapi.o \
		wave4-vdi.o \
		wave4-vpu-dec.o \
		wave4-vpu.o \
		wave4-vpu-enc.o \
		wave4-helper.o
